### ISSUE TITLE
CircularProgressIndicator covers the whole view

### ISSUE THREAD

**Issue by jakub-cosmose** [omchiii/model_viewer_plus.dart#10]
**Describe the bug**
After adding the `CircularProgressIndicator` the WebView is shown only if `_proxy == null`, so only in invalid state. The condition should be `!= null`. Apart from that, the state is not refreshed when the proxy is created, so it works pretty random, sometimes the WebView is shown and sometimes the progress. Once one of them is shown, it never changes until the widget is refreshed externally.

**To reproduce**
1. Just open the example app; sometimes the progress stays there forever

**Expected behavior**
The progress should be shown only during proxy loading.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 12

**Comment by muazbutt9** [comment]
@jakub-cosmose the AR button is also mot working, it gives an intent error on click. Is it working for you?

**Comment by Foldblade** [comment]
Thank you! I'll have a check for that.
