### ISSUE TITLE
Gestures don't work when ModelViewer is inside ListView

### ISSUE THREAD

**Issue by jakub-cosmose** [omchiii/model_viewer_plus.dart#11]
**Describe the bug**
No scaling or rotating can be done when the component is inside `ListView`.

**To reproduce**
1. Put `ModelViewer` inside `ListView`, e.g.
```
         ListView(
          children: [
            Container(
              height: 300,
              child: ModelViewer(
                src: 'modelUrl',
                alt: 'A 3D model',
                ar: false,
                autoRotate: true,
                cameraControls: true,
              ),
            )
          ],
        ),
```
2. Try gestures

**Expected behavior**
Gestures should work

**Additional context**
The internal `WebView` should handle all gestures by adding the following property to the constructor:
```
      gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>{
        Factory<OneSequenceGestureRecognizer>(
              () => EagerGestureRecognizer(),
        ),
      },
```
Alternatively, there should be a way for the client app to enable that behaviour.

**Comment by Foldblade** [comment]
https://github.com/omchiii/model_viewer_plus.dart/pull/16/commits/bc65c0da2e08f241236a38095b01bdfa3ca72200 Thank you for your advice!
