### ISSUE TITLE
Can we edit models, add custom dots or iicons on model with this package?

### ISSUE THREAD

**Issue by GauravCalidig** [omchiii/model_viewer_plus.dart#20]
Need to use this package for an app where  users can add there home model and select empty area. is this feasible? a small example woud be great. thanks

**Comment by Foldblade** [comment]
This package is based on [model viewer](modelviewer.dev/), which is just for displaying interactive 3D models, for example, drag to see different angles.

Sorry but I think your needs of "interactive with the home model" may not be met.
