### ISSUE TITLE
Model Viewer not playing animations that included in glb file

### ISSUE THREAD

**Issue by PeterTF656** [omchiii/model_viewer_plus.dart#21]
Running on Chrome.

I tried to recreate the animated 3d [robot example](https://modelviewer.dev/examples/animation/index.html) (made by google model viewer official) using the RobotExpressive.glb file downloaded here https://modelviewer.dev/editor/. However, model viewer widget only renders the 3d model but did not show the animation, and when I set `autoplay: true`, it gave me a warning: `Removing disallowed attribute <MODEL-VIEWER autoplay="">`

Did anyone else run into similar issues?

**Comment by Foldblade** [comment]
I think I've found the problem. 

There is a space after https://github.com/omchiii/model_viewer_plus.dart/blob/c7a1204a545c6a6293b1abdfade699219244d76e/lib/src/model_viewer_plus_web.dart#L85

I'm making some updates, this will be fixed soon.
