### ISSUE TITLE
Generate posters

### ISSUE THREAD

**Issue by Yehoyakim** [omchiii/model_viewer_plus.dart#23]
Hello everyone,
I want to know if it is possible to generate posters, I know that it is possible with the original model-viewer, but the pub documentation does not say anything about it.

if not currently available, any suggestions on how to get a picture of the model would be greatly appreciated.

**Comment by Foldblade** [comment]
Do you mean the poster when loading? This is supported since our 1.2.0 😆 

https://pub.dev/documentation/model_viewer_plus/latest/model_viewer_plus/ModelViewer/poster.html

**Comment by Yehoyakim** [comment]
My bad, I was trying to refer to the [toDataURL](https://modelviewer.dev/docs/#entrydocs-loading-methods-toDataURL) function

**Comment by Foldblade** [comment]
Sadly, methods are not currently supported.😢

I’m willing to look into it, but it's hard to say if I can implement this feature…

**Comment by muazbutt9** [comment]
@Foldblade any update on the poster feature, as it's necessary to display image until the 3D model loads
