### ISSUE TITLE
is it possible to display multiple 3d models?

### ISSUE THREAD

**Issue by kibu7** [omchiii/model_viewer_plus.dart#29]
is it possible to display multiple 3d models?
I have two ModelViewer but both are diplaying the same model

My code: 
`SizedBox(
              height: 300,
              width: 300,
              child: ModelViewer(
                src:
                    'https://modelviewer.dev/shared-assets/models/Astronaut.glb',
                alt: "A 3D model of an astronaut",
                ar: true,
                autoRotate: true,
                cameraControls: true,
              ),
            ),
            SizedBox(
              height: 500,
              width: 500,
              child: ModelViewer(
                src:
                    'https://modelviewer.dev/shared-assets/models/NeilArmstrong.glb',
                alt: "A 3D model of an astronaut",
                ar: true,
                autoRotate: true,
                cameraControls: true,
              ),
            ),`
is there a way to displaying mutliple or can i just display one 3d model?
thank you for tips

**Comment by Foldblade** [comment]
Hello @kibu7 @jamesninnes, guessing you both using `model_viewer_plus` on Web?

I think I've found the problem: #31
