### ISSUE TITLE
Build failing after adding package

### ISSUE THREAD

**Issue by Oneya4** [omchiii/model_viewer_plus.dart#3]
**Describe the bug**
I needed to add a 3D view in one of the screens in my app. Initially I got proper builds but after adding this package build fails
**To reproduce**
1. Upgrade to flutter2.10.0
2. Create new project
3. Run build
4. Add package model_viewer_plus
5. Add (android:usesCleartextTraffic="true") property in the AndroidManifest.xml
6. Replace main.dart code with the example code on pub.dev

**Expected behavior**
Build runs and the view of .glb image appears

**Screenshots**
Gradle build error message.
![image](https://user-images.githubusercontent.com/46073127/153705002-b558e79b-b6ce-413d-8264-a99c70e75ca6.png)

The file I'm pointed to. I have tried running **flutter clean .pub-cache/hosted/pub.dartlang.org/** and increasing the minSdkVersion 21 to no success. I'm not sure whether I'm doing something wrong
![image](https://user-images.githubusercontent.com/46073127/153705121-66f518d3-6679-4761-a161-e0e715f767d9.png)
![image](https://user-images.githubusercontent.com/46073127/153705165-9fd2e070-0930-4f25-8d65-db2065fb33bb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - Device: SMA30s (Samsung)
 - Android 11
 - Samsung Internet
 - 16.0.6.23

**Comment by omchiii** [comment]
Try using these steps: 
1.    Create a new project
2.    run - "flutter pub add model_viewer_plus" in your terminal.
2.    In android/app/build.gradle change minSdkVersion to 19.
3.    In android/app/src/main/AndroidManifest.xml add android:usesCleartextTraffic="true" to the <application> XML file.

Run the project.  
If this does not work send the logs of running flutter in verbose mode -  "flutter run -v"

**Comment by Oneya4** [comment]
I have followed that process but still build is failing. As requested, here are the logs

flutter run -v

> [ +137 ms] executing: [E:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
> [+10204 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
> [   +3 ms] db747aa1331bd95bc9b3874c842261ca2d302cd5
> [   +4 ms] executing: [E:\flutter/] git tag --points-at db747aa1331bd95bc9b3874c842261ca2d302cd5       
> [+15898 ms] Exit code 0 from: git tag --points-at db747aa1331bd95bc9b3874c842261ca2d302cd5
> [   +2 ms] 2.10.1
> [  +72 ms] executing: [E:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
> [ +153 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
> [   +2 ms] origin/stable
> [   +1 ms] executing: [E:\flutter/] git ls-remote --get-url origin
> [ +233 ms] Exit code 0 from: git ls-remote --get-url origin
> [   +2 ms] https://github.com/flutter/flutter
> [ +628 ms] executing: [E:\flutter/] git rev-parse --abbrev-ref HEAD
> [ +164 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
> [ +172 ms] stable
> [ +980 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
> [   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
> [  +19 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
> [   +4 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
> [   +4 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
> [  +32 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
> [ +185 ms] executing: C:\Users\Winde\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
> [ +231 ms] List of devices attached
>                     transport_id:3
> [ +153 ms] C:\Users\Winde\AppData\Local\Android\sdk\platform-tools\adb.exe -s RZ8M92SK5FN shell getprop[ +262 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.      
> [   +3 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
> [+2603 ms] Downloading Web SDK...
> [+3111 ms] Content
> https://storage.googleapis.com/flutter_infra_release/flutter/ab46186b246f5a36bd1f3f295d14a43abb1e2f38/flutter-web-sdk-windows-x64.zip md5 hash: iV++0lkB7vKiFxPgaftiJw==
> Terminate batch job (Y/N)? Y
> PS C:\Users\Winde\Desktop\kitu> flutter run -v
> [ +150 ms] executing: [E:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
> [+6194 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
> [   +4 ms] db747aa1331bd95bc9b3874c842261ca2d302cd5
> [   +4 ms] executing: [E:\flutter/] git tag --points-at db747aa1331bd95bc9b3874c842261ca2d302cd5       
> [+26618 ms] Exit code 0 from: git tag --points-at db747aa1331bd95bc9b3874c842261ca2d302cd5
> [   +3 ms] 2.10.1
> [  +72 ms] executing: [E:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
> [ +571 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
> [   +2 ms] origin/stable
> [   +1 ms] executing: [E:\flutter/] git ls-remote --get-url origin
> [ +284 ms] Exit code 0 from: git ls-remote --get-url origin
> [   +2 ms] https://github.com/flutter/flutter
> [ +549 ms] executing: [E:\flutter/] git rev-parse --abbrev-ref HEAD
> [ +127 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
> [   +1 ms] stable
> [+1233 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
> [   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
> [   +3 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
> [  +19 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
> [   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
> [   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
> [ +331 ms] executing: C:\Users\Winde\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
> [ +389 ms] List of devices attached
>                     RZ8M92SK5FN            device product:a30sxx model:SM_A307FN device:a30s
>                     transport_id:3
> [ +412 ms] C:\Users\Winde\AppData\Local\Android\sdk\platform-tools\adb.exe -s RZ8M92SK5FN shell getprop[ +333 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.      
> [   +3 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
> [  +38 ms] Downloading Web SDK...
> [+1774 ms] Content
> https://storage.googleapis.com/flutter_infra_release/flutter/ab46186b246f5a36bd1f3f295d14a43abb1e2f38/flutter-web-sdk-windows-x64.zip md5 hash: iV++0lkB7vKiFxPgaftiJw==
> [+371682 ms] Downloading Web SDK... (completed in 372.8s)
> [+108865 ms] Downloading CanvasKit...
> [+1446 ms] Content
> https://chrome-infra-packages.appspot.com/dl/flutter/web/canvaskit_bundle/+/8MSYGWVWzrTJIoVL00ZquruZs-weuwLBy1kt1AawJiIC md5 hash: aaW7noKw3KtLgNR1YJEqUQ==
> [+20816 ms] Downloading CanvasKit... (completed in 22.3s)
> [+2399 ms] Downloading windows-x64/windows-x64-flutter tools...
> [ +406 ms] Content
> https://storage.googleapis.com/flutter_infra_release/flutter/ab46186b246f5a36bd1f3f295d14a43abb1e2f38/windows-x64/windows-x64-flutter.zip md5 hash: /BlBEgqkSjAZ83Qz7uEaFQ==
> [+163127 ms] Downloading windows-x64/windows-x64-flutter tools... (completed in 163.5s)
> [+23420 ms] Downloading windows-x64/flutter-cpp-client-wrapper tools...
> [  +35 ms] Content
> https://storage.googleapis.com/flutter_infra_release/flutter/ab46186b246f5a36bd1f3f295d14a43abb1e2f38/windows-x64/flutter-cpp-client-wrapper.zip md5 hash: GiYYNMYrsdEshykSzy+WvQ==
> [  +83 ms] Downloading windows-x64/flutter-cpp-client-wrapper tools... (completed in 114ms)
> [+1285 ms] Downloading windows-x64-profile/windows-x64-flutter tools...
> [ +500 ms] Content
> https://storage.googleapis.com/flutter_infra_release/flutter/ab46186b246f5a36bd1f3f295d14a43abb1e2f38/windows-x64-profile/windows-x64-flutter.zip md5 hash: hmUMuETIxZ/jdcRlnZeNmg==
> [+175278 ms] Downloading windows-x64-profile/windows-x64-flutter tools... (completed in 175.8s)
> [+22001 ms] Downloading windows-x64-release/windows-x64-flutter tools...
> [ +319 ms] Content
> https://storage.googleapis.com/flutter_infra_release/flutter/ab46186b246f5a36bd1f3f295d14a43abb1e2f38/windows-x64-release/windows-x64-flutter.zip md5 hash: oRuhgYWCwaXSYhSCK+mI3w==
> [+161447 ms] Downloading windows-x64-release/windows-x64-flutter tools... (completed in 161.8s)
> [+19818 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
> [   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
> [  +18 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
> [   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
> [+4142 ms] Skipping pub get: version match.
> [ +143 ms] Found plugin android_intent_plus at
> E:\flutter\.pub-cache\hosted\pub.dartlang.org\android_intent_plus-3.0.2\
> [+2575 ms] Found plugin webview_flutter at
> E:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-3.0.0\
> [  +97 ms] Found plugin webview_flutter_android at
> E:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter_android-2.8.2\
> [ +166 ms] Found plugin webview_flutter_wkwebview at
> E:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter_wkwebview-2.7.1\
> [+1738 ms] Found plugin android_intent_plus at
> E:\flutter\.pub-cache\hosted\pub.dartlang.org\android_intent_plus-3.0.2\
> [+1756 ms] Found plugin webview_flutter at
> E:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-3.0.0\
> [   +5 ms] Found plugin webview_flutter_android at
> E:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter_android-2.8.2\
> [   +7 ms] Found plugin webview_flutter_wkwebview at
> E:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter_wkwebview-2.7.1\
> [ +347 ms] Generating
> C:\Users\Winde\Desktop\kitu\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java[+2045 ms] ro.hardware = exynos7904
> [   +1 ms] ro.build.characteristics = phone
> [ +720 ms] Initializing file store
> [ +297 ms] Skipping target: gen_localizations
> [  +61 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The
> following inputs have updated contents: C:\Users\Winde\Desktop\kitu\.dart_tool\package_config_subset}  
> [  +68 ms] Found plugin android_intent_plus at
> E:\flutter\.pub-cache\hosted\pub.dartlang.org\android_intent_plus-3.0.2\
> [  +65 ms] Found plugin webview_flutter at
> E:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-3.0.0\
> [   +5 ms] Found plugin webview_flutter_android at
> E:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter_android-2.8.2\
> [   +8 ms] Found plugin webview_flutter_wkwebview at
> E:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter_wkwebview-2.7.1\
> [   +7 ms] gen_dart_plugin_registrant: Complete
> [   +8 ms] Skipping target: _composite
> [   +3 ms] complete
> [  +13 ms] Launching lib\main.dart on SM A307FN in debug mode...
> [  +15 ms] E:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
> E:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
> E:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter       
> --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dillC:\Users\Winde\AppData\Local\Temp\flutter_tools.96693a59\flutter_tool.95949223\app.dill --packages     
> C:\Users\Winde\Desktop\kitu\.dart_tool\package_config.json -Ddart.vm.profile=false
> -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root 
> --initialize-from-dill build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
> --enable-experiment=alternative-invalidation-strategy
> [ +383 ms] executing: C:\Users\Winde\AppData\Local\Android\sdk\platform-tools\adb.exe -s RZ8M92SK5FN
> shell -x logcat -v time -t 1
> [ +210 ms] <- compile package:kitu/main.dart
> [ +330 ms] adb.exe: device 'RZ8M92SK5FN' not found
> [  +17 ms] Failed to extract the most recent timestamp from the Android log: ProcessException: Process
> exited
>            abnormally:
>            adb.exe: device 'RZ8M92SK5FN' not found
>              Command: C:\Users\Winde\AppData\Local\Android\sdk\platform-tools\adb.exe -s RZ8M92SK5FN   
> shell -x
>              logcat -v time -t 1.
> [  +48 ms] executing: C:\Users\Winde\AppData\Local\Android\sdk\platform-tools\adb.exe version
> [  +73 ms] Android Debug Bridge version 1.0.41
>            Version 31.0.3-7562133
>            Installed as C:\Users\Winde\AppData\Local\Android\sdk\platform-tools\adb.exe
> [   +4 ms] executing: C:\Users\Winde\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
> [  +58 ms] Building APK
> [ +643 ms] Running Gradle task 'assembleDebug'...
> [ +185 ms] Using gradle from C:\Users\Winde\Desktop\kitu\android\gradlew.bat.
> [+1564 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
> [+5167 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
> [   +2 ms] openjdk version "1.8.0_242-release"
>            OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>            OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
> [ +144 ms] executing: [C:\Users\Winde\Desktop\kitu\android/]
> C:\Users\Winde\Desktop\kitu\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64
> -Ptarget=C:\Users\Winde\Desktop\kitu\lib\main.dart -Pbase-application-name=android.app.Application     
> -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false
> -Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root
> assembleDebug
> [+37585 ms]
> /E:/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-3.0.0/lib/webview_flutter.dart: Error:  
> The control character U+0000 can only be used in strings and comments.
> [+36813 ms]
> /E:/flutter/.pub-cache/hosted/pub.dartlang.org/model_viewer_plus-1.0.2+1/lib/src/model_viewer_plus.dart:93:19: Error: Type 'WebViewController' not found.
> [   +3 ms]   final Completer<WebViewController> _controller =
> [   +1 ms]                   ^^^^^^^^^^^^^^^^^
> [+6964 ms]
> /E:/flutter/.pub-cache/hosted/pub.dartlang.org/model_viewer_plus-1.0.2+1/lib/src/model_viewer_plus.dart:93:19: Error: 'WebViewController' isn't a type.
> [   +9 ms]   final Completer<WebViewController> _controller =
> [   +2 ms]                   ^^^^^^^^^^^^^^^^^
> [   +9 ms]
> /E:/flutter/.pub-cache/hosted/pub.dartlang.org/model_viewer_plus-1.0.2+1/lib/src/model_viewer_plus.dart:94:17: Error: 'WebViewController' isn't a type.
> [  +21 ms]       Completer<WebViewController>();
> [   +4 ms]                 ^^^^^^^^^^^^^^^^^
> [   +4 ms]
> /E:/flutter/.pub-cache/hosted/pub.dartlang.org/model_viewer_plus-1.0.2+1/lib/src/model_viewer_plus.dart:125:32: Error: 'WebViewController' isn't a type.
> [   +2 ms]       onWebViewCreated: (final WebViewController webViewController) async {
> [   +2 ms]                                ^^^^^^^^^^^^^^^^^
> [        ]
> /E:/flutter/.pub-cache/hosted/pub.dartlang.org/model_viewer_plus-1.0.2+1/lib/src/model_viewer_plus.dart:133:34: Error: 'NavigationRequest' isn't a type.
> [   +4 ms]       navigationDelegate: (final NavigationRequest navigation) async {
> [        ]                                  ^^^^^^^^^^^^^^^^^
> [        ]
> /E:/flutter/.pub-cache/hosted/pub.dartlang.org/model_viewer_plus-1.0.2+1/lib/src/model_viewer_plus.dart:165:34: Error: 'WebResourceError' isn't a type.
> [   +2 ms]       onWebResourceError: (final WebResourceError error) {
> [   +2 ms]                                  ^^^^^^^^^^^^^^^^
> [   +2 ms]
> /E:/flutter/.pub-cache/hosted/pub.dartlang.org/model_viewer_plus-1.0.2+1/lib/src/model_viewer_plus.dart:121:12: Error: The method 'WebView' isn't defined for the class '_ModelViewerState'.
> [   +3 ms]  - '_ModelViewerState' is from 'package:model_viewer_plus/src/model_viewer_plus.dart'       
> ('/E:/flutter/.pub-cache/hosted/pub.dartlang.org/model_viewer_plus-1.0.2+1/lib/src/model_viewer_plus.dart').
> [   +2 ms] Try correcting the name to the name of an existing method, or defining a method named       
> 'WebView'.
> [   +3 ms]     return WebView(
> [   +5 ms]            ^^^^^^^
> [        ]
> /E:/flutter/.pub-cache/hosted/pub.dartlang.org/model_viewer_plus-1.0.2+1/lib/src/model_viewer_plus.dart:123:23: Error: The getter 'JavascriptMode' isn't defined for the class '_ModelViewerState'.
> [   +2 ms]  - '_ModelViewerState' is from 'package:model_viewer_plus/src/model_viewer_plus.dart'       
> ('/E:/flutter/.pub-cache/hosted/pub.dartlang.org/model_viewer_plus-1.0.2+1/lib/src/model_viewer_plus.dart').
> [   +1 ms] Try correcting the name to the name of an existing getter, or defining a getter or field    
> named 'JavascriptMode'.
> [   +2 ms]       javascriptMode: JavascriptMode.unrestricted,
> [   +1 ms]                       ^^^^^^^^^^^^^^
> [   +1 ms]
> /E:/flutter/.pub-cache/hosted/pub.dartlang.org/model_viewer_plus-1.0.2+1/lib/src/model_viewer_plus.dart:124:35: Error: The getter 'AutoMediaPlaybackPolicy' isn't defined for the class '_ModelViewerState'.  
> [   +7 ms]  - '_ModelViewerState' is from 'package:model_viewer_plus/src/model_viewer_plus.dart'
> ('/E:/flutter/.pub-cache/hosted/pub.dartlang.org/model_viewer_plus-1.0.2+1/lib/src/model_viewer_plus.dart').
> [   +1 ms] Try correcting the name to the name of an existing getter, or defining a getter or field    
> named 'AutoMediaPlaybackPolicy'.
> [   +1 ms]       initialMediaPlaybackPolicy: AutoMediaPlaybackPolicy.always_allow,
> [   +1 ms]                                   ^^^^^^^^^^^^^^^^^^^^^^^
> [   +1 ms]
> /E:/flutter/.pub-cache/hosted/pub.dartlang.org/model_viewer_plus-1.0.2+1/lib/src/model_viewer_plus.dart:136:18: Error: The getter 'NavigationDecision' isn't defined for the class '_ModelViewerState'.       
> [   +4 ms]  - '_ModelViewerState' is from 'package:model_viewer_plus/src/model_viewer_plus.dart'       
> ('/E:/flutter/.pub-cache/hosted/pub.dartlang.org/model_viewer_plus-1.0.2+1/lib/src/model_viewer_plus.dart').
> [   +3 ms] Try correcting the name to the name of an existing getter, or defining a getter or field    
> named 'NavigationDecision'.
> [   +1 ms]           return NavigationDecision.navigate;
> [   +1 ms]                  ^^^^^^^^^^^^^^^^^^
> [   +3 ms]
> /E:/flutter/.pub-cache/hosted/pub.dartlang.org/model_viewer_plus-1.0.2+1/lib/src/model_viewer_plus.dart:139:18: Error: The getter 'NavigationDecision' isn't defined for the class '_ModelViewerState'.       
> [   +3 ms]  - '_ModelViewerState' is from 'package:model_viewer_plus/src/model_viewer_plus.dart'
> ('/E:/flutter/.pub-cache/hosted/pub.dartlang.org/model_viewer_plus-1.0.2+1/lib/src/model_viewer_plus.dart').
> [   +7 ms] Try correcting the name to the name of an existing getter, or defining a getter or field    
> named 'NavigationDecision'.
> [   +1 ms]           return NavigationDecision.navigate;
> [   +3 ms]                  ^^^^^^^^^^^^^^^^^^
> [        ]
> /E:/flutter/.pub-cache/hosted/pub.dartlang.org/model_viewer_plus-1.0.2+1/lib/src/model_viewer_plus.dart:157:16: Error: The getter 'NavigationDecision' isn't defined for the class '_ModelViewerState'.       
> [   +2 ms]  - '_ModelViewerState' is from 'package:model_viewer_plus/src/model_viewer_plus.dart'       
> ('/E:/flutter/.pub-cache/hosted/pub.dartlang.org/model_viewer_plus-1.0.2+1/lib/src/model_viewer_plus.dart').
> [   +2 ms] Try correcting the name to the name of an existing getter, or defining a getter or field    
> named 'NavigationDecision'.
> [   +5 ms]         return NavigationDecision.prevent;
> [   +4 ms]                ^^^^^^^^^^^^^^^^^^
> [+178810 ms] FAILURE: Build failed with an exception.
> [  +10 ms] * What went wrong:
> [   +2 ms] A problem occurred configuring project ':android_intent_plus'.
> [   +4 ms] > Could not load compiled classes for build file
> 'E:\flutter\.pub-cache\hosted\pub.dartlang.org\android_intent_plus-3.0.2\android\build.gradle' from    
> cache.
> [  +15 ms] > Failed to notify project evaluation listener.
> [   +2 ms]    > Could not get unknown property 'android' for project ':android_intent_plus' of type    
> org.gradle.api.Project.
> [   +7 ms]    > Could not get unknown property 'android' for project ':android_intent_plus' of type    
> org.gradle.api.Project.
> [   +6 ms] * Try:
> [   +2 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to   
> get more log output. Run with --scan to get full insights.
> [   +9 ms] * Get more help at https://help.gradle.org
> [+1015 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
> [   +5 ms] Use '--warning-mode all' to show the individual deprecation warnings.
> [   +1 ms] See
> https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
> [  +16 ms] BUILD FAILED in 4m 12s
> [+2525 ms] Running Gradle task 'assembleDebug'... (completed in 271.0s)
> [  +14 ms] Exception: Gradle task assembleDebug failed with exit code 1
> [  +76 ms] "flutter run" took 1,363,494ms.
> [ +186 ms] 
>                     #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
>                     #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)  
>                     <asynchronous suspension>
>                     #2      FlutterCommand.run.<anonymous closure>
>                     (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
>                     <asynchronous suspension>
>                     #3      AppContext.run.<anonymous closure>
> (package:flutter_tools/src/base/context.dart:150:19)
>                     <asynchronous suspension>
>                     #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
>                     <asynchronous suspension>
>                     #5      FlutterCommandRunner.runCommand.<anonymous closure>
>                     (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
>                     <asynchronous suspension>
>                     #6      AppContext.run.<anonymous closure>
> (package:flutter_tools/src/base/context.dart:150:19)
>                     <asynchronous suspension>
>                     #7      FlutterCommandRunner.runCommand
>                     (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
>                     <asynchronous suspension>
>                     #8      run.<anonymous closure>.<anonymous closure>
> (package:flutter_tools/runner.dart:62:9)
>                     <asynchronous suspension>
>                     #9      AppContext.run.<anonymous closure>
>                     <asynchronous suspension>
>                     #10     main (package:flutter_tools/executable.dart:94:3)
>                     <asynchronous suspension>
> 
> 
> [ +318 ms] ensureAnalyticsSent: 261ms
> [   +4 ms] Running shutdown hooks
> [   +1 ms] Shutdown hooks complete
> [   +1 ms] exiting with code 1

**Comment by omchiii** [comment]
The package was updated. Try running the latest version of the package end let us know if it is fixed!

**Comment by husky-wdy** [comment]
How to solve?
