### ISSUE TITLE
Flutter v3 issues

### ISSUE THREAD

**Issue by Kerrely** [omchiii/model_viewer_plus.dart#34]
**Description**
Several issues have been found while trying to use the package on Flutter v3 project. (Even when using the unchanged example project in this repo)

Happens on **Android** devices only.

**Flutter 3.0.5**
(all steps for setup from README have been followed)
- `ModelViewer` causes the app to crash on Android devices - found out that there are apparently some problems within the versions of used dependencies (such as WebView). Note that there are no issues on iOS devices. 
- The log in the console from the crash event is really long (filled with messages mostly from the native environment) and the only part that makes sense is the following:
```
[ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.IllegalStateException: Platform view hasn't been initialized from the platform view channel.
E/flutter ( 5700): 	at io.flutter.plugin.platform.PlatformViewsController.initializePlatformViewIfNeeded(PlatformViewsController.java:732)
```

**Flutter 3.1.0**
(all steps for setup from README have been followed)
- App does not crash anymore but the first load does not happen  (pop and push the page with `ModelViewer` magically fixes the problem) giving the following error to the console (white screen is provided instead):
```
ModelViewer initializing... <http://127.0.0.1:40991/>
W/(13480): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (unsupported, reflection, allowed)
W/cr_media(13480): Requires BLUETOOTH permission
E/flutter (13480): [ERROR:flutter/runtime/dart_vm_initializer.cc(39)] Unhandled Exception: Bad state: Future already completed
E/flutter (13480): #0      _AsyncCompleter.complete (dart:async/future_impl.dart:35:31)
E/flutter (13480): #1      _WebViewState._onWebViewPlatformCreated (package:webview_flutter/src/webview.dart:348:17)
E/flutter (13480): #2      SurfaceAndroidWebView.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:webview_flutter_android/webview_surface_android.dart:83:43)
E/flutter (13480): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:766:15)
E/flutter (13480): <asynchronous suspension>
```

**To reproduce**
Use either Flutter 3.0.5 or 3.1.0 and use the example or own implementation of the package by simply using the `ModelViewer` widget and providing it with a valid 3D model. Then run the app and see the page with model viewer.

**Expected behavior**
The model viewer displays the object without any issues on the first attempt.

**Screenshots**
There's nothing to see as in the first case the app crashes and in the second one is the first load represented by white page.

**Additional context**
None of those issues appear on iOS devices. Tried on several different Android versions and devices - none of it worked.

**Flutter doctor**
3.1.0:
```
[√] Flutter (Channel beta, 3.1.0, on Microsoft Windows [Version 10.0.22000.795], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.69.1)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

3.0.5:
```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.795], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.69.1)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

**Comment by sine233** [comment]
has same issue

**Comment by Foldblade** [comment]
Hello @Kerrely, I upgrade my Flutter SDK to 

- Channel beta, 3.1.0
- Channel stable, 3.0.5
- Channel beta, 3.3.0-0.0.pre

but on my Android device, these SDK versions with `model_viewer_plus` v1.3.0 all work well.

Could you post the version of `model_viewer_plus` you use?

I also noticed you methoned that _"there are apparently some problems within the versions of used dependencies (such as WebView)"_, so I made a pull request (#35), please have a try from the git or after it been published to pub.dev by @omchiii  (the version should be v1.3.1) 😉

**Comment by Foldblade** [comment]
> has same issue

Hello @sine233, could you provide the version of `model_viewer_plus` you use and your flutter doctor? 

Just as I replied above, I can't reproduce the issue. Could you try #35 or maybe the v1.3.1 on pub.dev?

**Comment by Kerrely** [comment]
It helped! Thank you 😁
