### ISSUE TITLE
Error setting minCameraOrbit

### ISSUE THREAD

**Issue by shaun-man** [omchiii/model_viewer_plus.dart#40]
**Describe the bug**
The value of minCameraOrbit becomes HTML attribute max-camera-orbit in the output build. Line 285 in file html_builder.dart generates this error.

**To reproduce**
1. Set up ModelViewer with minCameraOrbit: "auto 89deg auto"
2. Build for web or Android device
3. The Debug or Run tab will show that the generated model-viewer element has attribute ' max-camera-orbit="auto 89deg auto" ' instead of ' min-camera-orbit="auto 89deg auto" ', and in the running web app DevTools shows the same attribute

**Expected behavior**
If one sets up ModelViewer with minCameraOrbit: "auto 89deg auto" then the generated model-viewer element should contain attribute ' min-camera-orbit="auto 89deg auto" '

**Comment by Foldblade** [comment]
Thank You! #41 should fix this issue.
