### ISSUE TITLE
Script file model-viewer.min.js not added to web app

### ISSUE THREAD

**Issue by shaun-man** [omchiii/model_viewer_plus.dart#42]
**Describe the bug**
Script file model-viewer.min.js not added to web app

**To reproduce**
1. Copy example app to Android Studio Flutter project
2. Build for Chrome or Edge
3. Model does not appear. Inspect with DevTools, you will see that script file model-viewer.min.js is not included

**Expected behavior**
Model should appear.

**Workaround**
Added the following line to the head element in project_name\web\index.html :
    <script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></script>

**Comment by Foldblade** [comment]
Recently `<model-viewer>` upgraded to 2.0.0, and we have not keep up to it. I will make more updates later.

In #45, we updated the `README.md`. Please try to use:

```
<script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js" defer></script>
```

instead of 

```
<script type="module" src="./assets/packages/model_viewer_plus/assets/model-viewer.min.js" defer></script>
```
