### ISSUE TITLE
Web app gets sanitized

### ISSUE THREAD

**Issue by shaun-man** [omchiii/model_viewer_plus.dart#43]
**Describe the bug**
Web app gets sanitized when running

**To reproduce**
1. Using Android Studio Flutter dev environment, create project using the example Model Viewer Plus app
2. Add button element (see below) via innerModelViewerHtml, add any JS via relatedJs
3. Build for Chrome or Edge
4. Look in the Run tab, messages appear saying "Removing disallowed element ..." and "Removing disallowed attribute ..."
5. In the debug browser, the button appears top left instead of on the model
6. Use DevTools to see that the script element was removed, and attributes of the button have been removed

**Expected behavior**
The web app includes the button element and the script element exactly as specified in main.dart

**More details**
Here is the button element that you can use for testing:
    ''' <button id="hole1" class="Hotspot" slot="hotspot-1" data-position="-0.0974717897178938m 0.17205803103940326m 0.06275803103940326m" data-normal="0m 0m 0.01m" data-visibility-attribute="visible">
        <div class="HotspotAnnotation">Hole 1</div>
    </button> '''

**Comment by Foldblade** [comment]
Sorry for that. Please try #45.
