### ISSUE TITLE
Implement minimumRenderScale API

### ISSUE THREAD

**Issue by DanielusG** [omchiii/model_viewer_plus.dart#44]
I recently used this package in a flutter web application of mine, it works really well, only on all the mobile devices on which I tested my site, the render quality is really low. While on pc it displays correctly. As the documentation reports this is normal and is called Dynamic scaling (https://modelviewer.dev/examples/loading/#renderScale)

I would like to have it implemented in the package, but I would also just need to be able to do it manually somehow I tried some code with the relatedJS parameter, but in the console it would come up "Removing disallowed element <SCRIPT> from [object DocumentFragment]" whatever I wrote.

Could you give me suggestions on how to implement it manually?

Thank you very much for what you do :)

**Comment by Foldblade** [comment]
Sorry for that. This is related with #43.

Because not all the elements are allowed in [`HtmlElementView`](https://api.flutter.dev/flutter/widgets/HtmlElementView-class.html), that's why `Removing disallowed element <SCRIPT> from [object DocumentFragment]` occured. By adding:

```
..allowElement('script',
          attributes: [
            'src',
            'type',
            'defer',
            'async',
            'crossorigin',
            'integrity',
            'nomodule',
            'nonce',
            'referrerpolicy'
          ],
          uriPolicy: _AllowUriPolicy())
```

to NodeValidatorBuilder.common() should make `<scripts>` with listed attributes avilable.

As a temporary solution, in PR #45, I also added a new example: `example/lib/loading/render_scale.dart`.

I just have no idea about how to implement the Javascript method in Dart... It would be great if you can help! 🥺

**Comment by DanielusG** [comment]
hello, thanks for the reply, I tried the example and on my smartphone the quality is still low, it's like model-viewer ignores the js script
this is a picture of how it looks on my smartphone:
![Screenshot_2022-09-18-15-29-04-35_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/78654556/190904761-0ab96eeb-9d90-4165-b518-02d9b3c7c057.jpg)

Doing research yesterday I had already applied the solution to bypass script blocking, but I got the same results, ignore js commands.
If you can create a working code snippet that renders in high quality I can implement it in dart. I am waiting to hear from you :)

**Comment by DanielusG** [comment]
the biggest mystery is that the model-viewer documentation snippet works fine on my phone and shows up in high quality. it seems to be just a problem with this library

**Comment by DanielusG** [comment]
I found that by removing from assets/template.html
the content parameter the render becomes in high quality but the whole page becomes small as if it were in desktop mode can this workaround be combined with something?

what i have done is change the first line of the template.html file to:
`<meta name="viewport" content="" />`

**Comment by Foldblade** [comment]
> I found that by removing from assets/template.html the content parameter the render becomes in high quality but the whole page becomes small as if it were in desktop mode can this workaround be combined with something?
> 
> what i have done is change the first line of the template.html file to: `<meta name="viewport" content="" />`

Sorry for the late reply.

Could you have a try, adding `<meta name="viewport" content="width=device-width, initial-scale=1" />` to your `web/index.html` to see if this solve the problem?

**Comment by DanielusG** [comment]
YES!!! the modification works perfectly, now on the devices can be seen in very good quality, thank you very much.
I specify that the only modification I made is the one you suggested, so I did not use the JavaScript script with the minimumRenderScale

thanks a lot for the help :)

**Comment by Foldblade** [comment]
You are welcome 😉

**Comment by Muhammad-Faizmf** [comment]
is there any way to disable scaling in AR mode
