### ISSUE TITLE
A PR was made, tried to add Web Support.

### ISSUE THREAD

**Issue by Foldblade** [omchiii/model_viewer_plus.dart#5]
<small>English is not my native language; please excuse typing errors.</small>

**Is your feature request related to a problem? Please describe.**
I'm developing an APP for Android and Web, hoping to use model-viewer on the Flutter Web, so I tried to add Web support for this package.

**Describe the solution you'd like**
#4 

**Additional context**
Wish my PR can help make this package further "plus" than the original model-viewer package😆

---

If you are willing to accept my PR, I will be grateful and hope to discuss the following issues with you: 

1. `etc\assets\model-viewer.js` is 2.24 Mb. The newest `model-viewer.min.js` from the official site is 211.7 Kb. I also don't know the version of `etc\assets\model-viewer.js`. Should we change the js file to the official site's newest min.js for a slimmer package size?

2. When using this package on Flutter Web, is it better to download the js file from CDN or assets? Or, let the user make the decision? ( In my PR, it just downloads the min.js file from CDN)

**Comment by omchiii** [comment]
Thank you for your pull request. I will have a look into it. Your first point makes sense as well. Iam not sure about your second point however, do you have any suggestions?

**Comment by Foldblade** [comment]
I investigated two packages on pub.dev:
- https://pub.dev/packages/google_maps_flutter_web
- https://pub.dev/packages/printing

They all add the <script> to `web/index.html` file.  

Currently, in my PR, once the model-viewer will be shown (load the modified `etc\assets\template.html`), the browser starts to download the js file from CDN. This may take a while to download the js file before the model is displayed.

Maybe we should follow the above two packages, require the users to add the <script> to `web/index.html` file in the document, so that in theory the js file can be downloaded while the Web Application is loading, and a faster display of the 3D Model.

By the way, `etc\assets\model-viewer.js` seems quite an old version. Currently, official site's version is something like <script **type="module"** src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></script> instead of <script src="model-viewer.js" defer></script> in `etc\assets\template.html`. We should take a notice when replacing `etc\assets\model-viewer.js`.

I'm willing to continue to improve my Web support. If you agree to the issues listed above, shall I open a new PR or wait for you to merge it first?

**Comment by omchiii** [comment]
If you could have it all in one PR it would be great!

**Comment by omchiii** [comment]
merged
