### ISSUE TITLE
Unable to play videos from firebase or public links

### ISSUE THREAD

**Issue by vanshaj-sc** [omchiii/model_viewer_plus.dart#52]
I have few glb videos uploaded on my firebase storage but when I try to play video from the url it throws me cors error, same is the issue with server hosted links
"Access to fetch at 'https://firebasestorage.googleapis.com/v0/b/bwcnnct.appspot.com/o/exerciseVideos%2Fsquats_1.glb?alt=media&token=3004f539-ef8e-455c-97d8-a754fe5c2ba5' (redirected from 'http://127.0.0.1:45343/model') from origin 'http://127.0.0.1:45343/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.", source: http://127.0.0.1:45343/ (0)
but the link mention in example works

Why such behaviour?

Tried these links
https://firebasestorage.googleapis.com/v0/b/bwcnnct.appspot.com/o/exerciseVideos%2Fsquats_1.glb?alt=media&token=3004f539-ef8e-455c-97d8-a754fe5c2ba5

https://staging.rentcraze.com/public/mobile/Astronaut.glb

**Comment by Bingbing0311** [comment]
+1

**Comment by Foldblade** [comment]
I think this issue is not related with model-viewer-plus. You should try to add `Access-Control-Allow-Origin: *` to your server side's response header.

**Comment by vanshaj-sc** [comment]
I am using firebase
Tried the solution still not working
