### ISSUE TITLE
Can this plugin display `stl` file? If so, how to display it? 

### ISSUE THREAD

**Issue by okerivy** [omchiii/model_viewer_plus.dart#56]
Hello, I want to display 3d files, Can this plugin display `stl` files? If so, how to display it? 
Here's an `stl` file

[fptest_wolf.stl.zip](https://github.com/omchiii/model_viewer_plus.dart/files/9959945/fptest_wolf.stl.zip)

**Comment by Foldblade** [comment]
Hello, this plugin is based on [<model-viewer>](https://modelviewer.dev/), so it only support `glb` / `gltf`. I prefer mark this issue as "won't fix".

But if you are a Windows user, there is a possible way to help you convert your `stl` files into `glb` / `gltf` files.

1. Open [3D Builder](https://apps.microsoft.com/store/detail/3d-builder/9WZDNCRFJ3T6) or [3D Viewer](https://apps.microsoft.com/store/detail/3d-viewer/9NBLGGH42THS) by Microsoft, which maybe system pre-installed.
2. Open your `stl` model using 3D Builder or 3D Viewer.
3. "Save as" your model in `glb` / `gltf` format.
4. Use <model-viewer>'s [Editor](https://modelviewer.dev/editor) to test your 3D models.
