### ISSUE TITLE
Change the color by pressing the buttons, but nothing happen [FLUTTER]

### ISSUE THREAD

**Issue by Thauanny** [omchiii/model_viewer_plus.dart#62]
**Describe the bug**
It is not possible to change the color of the obj as mentioned in the documentation " @https://modelviewer.dev/examples/scenegraph/#changeColor

**To reproduce**
![image](https://user-images.githubusercontent.com/44787914/211698294-e4ce715a-f289-43aa-ba3b-90f3aa664ef4.png)

**Expected behavior**
Change the color by pressing the buttons, but nothing happen

**Screenshots**
LOG:

![image](https://user-images.githubusercontent.com/44787914/211698253-bffeb455-e6ad-4e2c-a7f0-85c7c4e8b199.png)

Flutter web, android.

Flutter 3.4.0-29.0.pre.84 • channel master • https://github.com/flutter/flutter.git
Framework • revision c9edacb172 (4 months ago) • 2022-09-21 17:50:03 -0700
Engine • revision f0f4e1dee2
Tools • Dart 2.19.0 (build 2.19.0-226.0.dev) • DevTools 2.17.0

**Comment by Foldblade** [comment]
Hello, in #63 I added a new example: [example/lib/materials_and_scene/change_color.dart
](https://github.com/omchiii/model_viewer_plus.dart/pull/63/files#diff-fb1d916d92e47aa39e93b2cae4cdea0f0cd6946e381db4c1bb3458fd92d0b92e)
In the upcoming version, you can set `overwriteNodeValidatorBuilder` to solve this issue😉
