### ISSUE TITLE
Shadow don't work

### ISSUE THREAD

**Issue by jamesleetu** [omchiii/model_viewer_plus.dart#67]
Hello, Thank you for your great package :)

I want to remove the shadow in my model viewer but shadowIntensity & shadowSoftness don't work. I tried changing the value to 0.0~1.0 but nothing happens.

Can you help me to remove all the shadows in model viewer?

Thank you :)

**Comment by hanshanfeihe** [comment]
![image](https://github.com/omchiii/model_viewer_plus.dart/assets/53588055/0cceccd0-ad94-46c1-af82-4818db3c2635)
remove this "}"

**Comment by jamesleetu** [comment]
@hanshanfeihe Thx :)
