### ISSUE TITLE
Not able to update animation of GLB model

### ISSUE THREAD

**Issue by AqeelAaqi** [omchiii/model_viewer_plus.dart#68]
**Describe the bug**
Not able to update animation of GLB model.

**My code here below**
class ModelViewerScreen extends StatefulWidget {
  String animationName;
  ModelViewerScreen(this.animationName, {Key? key}) : super(key: key);

  @override
  State<ModelViewerScreen> createState() => _ModelViewerScreenState();
}

class _ModelViewerScreenState extends State<ModelViewerScreen> {
  

  @override
  void didUpdateWidget(covariant ModelViewerScreen oldWidget) {
    // TODO: implement didUpdateWidget
    print("didUpdateWidget === "+ widget.animationName);
    super.didUpdateWidget(oldWidget);
  }

  @override
  void didChangeDependencies() {
    // TODO: implement didChangeDependencies
    print("didChangeDependencies === "+ widget.animationName);
    super.didChangeDependencies();
  }
  @override
  Widget build(BuildContext context) {
    return ModelViewer(
      loading: Loading.auto,
      src: 'assets/RobotExpressive.glb',
      alt: "Bold [3D]",
      ar: false,
      exposure: 2,
      arModes: ['scene-viewer', 'webxr', 'quick-look'],
      skyboxImage: "https://modelviewer.dev/shared-assets/environments/spruit_sunrise_1k_HDR.hdr",
      interpolationDecay: 200,
      autoPlay: true,
      animationName: widget.animationName,
      animationCrossfadeDuration: 5000,
    );
  }
}

**Comment by reqdevil** [comment]
Hello, I finally found. If someone have similar problem. Add key parameter in modelViewer. It will change the state. My example code:

if (status == RoomStatus.study)
                  ModelViewer(
                    src: 'assets/model/work.glb',
                    disablePan: true,
                    autoPlay: true,
                    backgroundColor: AppColors.white,
                    key: const ValueKey('work'),
                  ),
                if (status == RoomStatus.recess)
                  ModelViewer(
                    src: 'assets/model/rest.glb',
                    disablePan: true,
                    autoPlay: true,
                    backgroundColor: AppColors.white,
                    key: const ValueKey('rest'),
                  ),

**Comment by AqeelAaqi** [comment]
Thanks, it's working for me but with the reload widget, actually i want update animation without reloading widget

**Comment by JudahMcNicholl** [comment]
Hello 
Please see my answer on this thread

https://github.com/omchiii/model_viewer_plus.dart/issues/66#issuecomment-1431915525
