### ISSUE TITLE
Error loading object in AR-View

### ISSUE THREAD

**Issue by pribbernow-marc** [omchiii/model_viewer_plus.dart#7]
**Describe the bug**
Clicking on the AR-Button (right bottom) I get an error: "Error loading object"

**To reproduce**
1. Checkout example project
2. Run project
3. Astronaut model is shown
4. Click on square button at the bottom

**Expected behavior**
An AR-View should be seen (like in the browser)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 5
 - OS: Android 12
 - Version: 1.1.2

**Additional context**
On iPhone I not even get the button to open in AR-View. However it works to see the model rotating in the ModelViewer.

**Comment by omchiii** [comment]
Did you run this on the Google pixel 5 emulator or physical device?

**Comment by muazbutt9** [comment]
> Did you run this on the Google pixel 5 emulator or physical device?

I am using physical device, tried several 3-4 android devices. Problem is same. 

When clicking AR view button showing object not found error. 

In terminal i am recieving an intent error. 

Please let me know what's the issue. How can it be fixed.
