### ISSUE TITLE
Remove the hand pointer when loading a 3D model 

### ISSUE THREAD

**Issue by TahaKh99** [omchiii/model_viewer_plus.dart#76]
I want to remove the highlighted hand pointer from the 3D model while keeping the camera controls set to true. 
I couldnt find the attribute which can do that except for cameraControls: but if I set it to false then the I cant rotate the model manually anymore. 

Is there a way to remove it while keeping camera control?
 
![image](https://user-images.githubusercontent.com/100087116/224599566-647cf3c4-bdf7-4580-b661-51f5110bed19.png)

**Comment by pledi** [comment]
Just saw you issue, you can hide the hand with the `interactionPrompt` attribute, just set it to `InteractionPrompt.none` and it's gone
