### ISSUE TITLE
ModelViewer works on emulators but not when apk is generated

### ISSUE THREAD

**Issue by MOmerShakeel** [omchiii/model_viewer_plus.dart#86]
Hello, i am using modelviewerplus with flutter and it seems to be working fine when i run on my virtual devices/emulators, but when I generate apk, the modelviewer widget shows nothing except constant loading sign. Kindly let me know what the issue might be.

**Comment by andrewda** [comment]
I had the same issue, and adding the internet permission to `android/app/src/main/AndroidManifest.xml` fixed the problem:

```xml
<uses-permission android:name="android.permission.INTERNET"/>
```

**Comment by MOmerShakeel** [comment]
Thankyou! This worked!
